<?php
/**
* My Google Custom Search Engine
*
* This search is set up to work with the two page search option. See: www.google.co.uk/cse/
*
*/
function unesco_google_cse_block_info() {
  // This example comes from node.module.
  $blocks['google_custom_search'] = array(
    'info' => t('My Google Custom Search'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


function unesco_google_cse_block_view($delta = '') {
  // This example is adapted from node.module.
  //$mymodule_testblock_content = '<gcse:searchbox-only></gcse:searchbox-only>';
  $block['title'] = t('');
  //drupal_add_js(drupal_get_path('module', 'unesco_google_cse') . '/unesco_google_cse.js', 'module', 'header');
  //$block['content'] = '<gcse:searchbox-only></gcse:searchbox-only>';
  $block['content'] = array(
    '#markup' => '<gcse:searchbox-only queryParameterName="as_q"></gcse:searchbox-only>',
    '#attached' => array(
        'js' => array(
          drupal_get_path('module', 'unesco_google_cse') . '/unesco_google_cse.js',
      ),
    ),
  );
  return $block;
    
}

// Here we set up the page:
function unesco_google_cse_searchpage() {
  // puts the call to your javascript file containing the Google code in the header
  // of the page:
  //drupal_add_js(drupal_get_path('module', 'unesco_google_cse') . '/unesco_google_cse.js');

  // Now create the content of your page:
  $content = '';
  // This is the search box again - so that it also appears at the top of the search
  // page.
  $content .= '<gcse:searchbox-only queryParameterName="as_q"></gcse:searchbox-only>';
  // Drupal search link:
  // This creates a link to the Drupal standard search from the Google results page:
  //$content .= l(t('Advanced search'), 'search/node/' . $_GET['as_q']);
  // This is the code for the results list.
  // Note we also add the queryParameterName setting here to the code. See
  // developers.google.com/custom-search/docs/element#supported_attributes
  // for a full list of supported attributes.
  // I've also set it so links to pages in the results open in the same window rather
  // than a new tab/window which is the default.
  $content .= '<gcse:searchresults-only queryParameterName="as_q" linkTarget="_self"></gcse:searchresults-only>';
  return $content;
}

/**
* Implementation of hook_menu()
*/
function unesco_google_cse_menu() {
  // Here we set up the page where the results will display:
  $items['search-results'] = array(  // Change this url to wherever you want the page to be
    'title' => 'Search ',
    'description' => 'My Google Custom Search',
    'page callback' => 'mygooglecse_searchpage', // The function that will be called to set up the search page
    'access arguments' => array('use_google_custom_search'), // Those with this permission will be allowed to see the results
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function unesco_google_cse_permission() {
  return array(
    'use_google_custom_search' => array(
      'title' => t('Use google custom search'),
      'description' => t('Who can have access to the google search results page.'),
    ),
  );
}
?>
